name: fuzzy
version: 0.4.1

description: >
  Fuzzy search in Dart. Initially a code conversion, subset of Fuse.js.
homepage: https://github.com/comigor/fuzzy

environment:
  sdk: ">=2.12.0-0.dev <3.0.0"

dependencies:
  latinize: ^0.1.0-nullsafety

dev_dependencies:
  test: ^1.16.0-nullsafety
  pedantic: ^1.10.0-nullsafety
